### ISSUE TITLE
Unsupported operation: Cannot modify an unmodifiable list

### ISSUE THREAD

**Issue by bibek-ranjan-saha** [AbdulrhmanSayedAli/vitality#2]
======== Exception caught by widgets library =======================================================
The following UnsupportedError was thrown building _BodyBuilder:
Unsupported operation: Cannot modify an unmodifiable list

The relevant error-causing widget was: 
  Scaffold Scaffold:file:///C:/Users/Bibek/AndroidStudioProjects/megnetoo_live/lib/pages/new_user.dart:29:12
When the exception was thrown, this was the stack: 
#0      UnmodifiableListMixin.shuffle (dart:_internal/list.dart:154:5)
#1      new ShapesGenerator.Randomly (package:vitality/shapesManagement/ShapesGenerator.dart:47:12)
#2      new _VitalityState (package:vitality/vitality.dart:135:33)
#3      Vitality.createState (package:vitality/vitality.dart:74:35)
#4      new StatefulElement (package:flutter/src/widgets/framework.dart:4842:25)
#5      StatefulWidget.createElement (package:flutter/src/widgets/framework.dart:770:38)
...     Normal element mounting (25 frames)
#30     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#31     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
#32     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433:32)
...     Normal element mounting (263 frames)
#295    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#296    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
#297    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433:32)
...     Normal element mounting (374 frames)
#671    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#672    Element.updateChild (package:flutter/src/widgets/framework.dart:3524:20)
#673    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#674    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#675    StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#676    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#677    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#678    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#679    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#680    _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:111:11)
#681    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#682    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#683    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4928:11)
#684    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#685    StatefulElement.update (package:flutter/src/widgets/framework.dart:4960:5)
#686    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#687    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#688    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#689    ProxyElement.update (package:flutter/src/widgets/framework.dart:5108:5)
#690    _InheritedProviderScopeElement.update (package:provider/src/inherited_provider.dart:523:11)
#691    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#692    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#693    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#694    StatelessElement.update (package:flutter/src/widgets/framework.dart:4834:5)
#695    Element.updateChild (package:flutter/src/widgets/framework.dart:3501:15)
#696    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4780:16)
#697    Element.rebuild (package:flutter/src/widgets/framework.dart:4477:5)
#698    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2659:19)
#699    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#700    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#701    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#702    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#703    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:862:7)
(elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)
====================================================================================================
Reloaded 1 of 1162 libraries in 682ms.

======== Exception caught by rendering library =====================================================
The following assertion was thrown during performLayout():
Each child must be laid out exactly once.

The _ScaffoldLayout custom multichild layout delegate forgot to lay out the following child: 
  _ScaffoldSlot.body: RenderErrorBox#23378 NEEDS-LAYOUT NEEDS-PAINT
    parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.body
    constraints: MISSING
    size: MISSING
The relevant error-causing widget was: 
  Scaffold Scaffold:file:///C:/Users/Bibek/AndroidStudioProjects/megnetoo_live/lib/pages/new_user.dart:29:12
When the exception was thrown, this was the stack: 
#0      MultiChildLayoutDelegate._callPerformLayout.<anonymous closure> (package:flutter/src/rendering/custom_layout.dart:243:11)
#1      MultiChildLayoutDelegate._callPerformLayout (package:flutter/src/rendering/custom_layout.dart:255:8)
#2      RenderCustomMultiChildLayoutBox.performLayout (package:flutter/src/rendering/custom_layout.dart:403:14)
#3      RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#4      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#5      RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#6      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#7      _RenderCustomClip.performLayout (package:flutter/src/rendering/proxy_box.dart:1376:11)
#8      RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#9      RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#10     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#11     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#12     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#13     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#14     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#15     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#16     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#17     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#18     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#19     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#20     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#21     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#22     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#23     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#24     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#25     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#26     RenderOffstage.performLayout (package:flutter/src/rendering/proxy_box.dart:3430:13)
#27     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#28     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#29     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#30     _RenderTheatre.performLayout (package:flutter/src/widgets/overlay.dart:751:15)
#31     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#32     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#33     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#34     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#35     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#37     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#38     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#39     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:545:11)
#40     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#41     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#42     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#43     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#44     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#46     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#47     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#48     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#49     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:116:14)
#50     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#51     RenderView.performLayout (package:flutter/src/rendering/view.dart:165:14)
#52     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1731:7)
#53     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
#54     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:497:19)
#55     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#56     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#57     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#58     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#59     SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:862:7)
(elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)
The following RenderObject was being processed when the exception was fired: RenderCustomMultiChildLayoutBox#53703 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=411.4, h=820.6)
...  size: Size(411.4, 820.6)
RenderObject: RenderCustomMultiChildLayoutBox#53703 NEEDS-LAYOUT NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=411.4, h=820.6)
  size: Size(411.4, 820.6)
...  child 1: RenderErrorBox#23378 NEEDS-LAYOUT NEEDS-PAINT
...    parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.body
...    constraints: MISSING
...    size: MISSING
...  child 2: RenderStack#399aa relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: offset=Offset(395.4, 804.6); id=_ScaffoldSlot.floatingActionButton (can use size)
...    constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=820.6)
...    size: Size(0.0, 0.0)
...    alignment: Alignment.centerRight
...    textDirection: ltr
...    fit: loose
...    child 1: RenderTransform#0aa61 relayoutBoundary=up2 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...      parentData: not positioned; offset=Offset(0.0, 0.0) (can use size)
...      constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=820.6)
...      size: Size(0.0, 0.0)
...      transform matrix: [0] 0.0,0.0,0.0,0.0
[1] 0.0,0.0,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
...      origin: null
...      alignment: Alignment.center
...      textDirection: ltr
...      transformHitTests: true
...      child: RenderTransform#4349c relayoutBoundary=up3 NEEDS-PAINT
...        parentData: <none> (can use size)
...        constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=820.6)
...        size: Size(0.0, 0.0)
...        transform matrix: [0] 0.7,0.7,0.0,0.0
[1] -0.7,0.7,0.0,0.0
[2] 0.0,0.0,1.0,0.0
[3] 0.0,0.0,0.0,1.0
...        origin: null
...        alignment: Alignment.center
...        textDirection: ltr
...        transformHitTests: true
...  child 3: RenderPositionedBox#02884 relayoutBoundary=up1 NEEDS-PAINT NEEDS-COMPOSITING-BITS-UPDATE
...    parentData: offset=Offset(0.0, 0.0); id=_ScaffoldSlot.body (can use size)
...    constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=820.6)
...    size: Size(411.4, 820.6)
...    alignment: Alignment.center
...    textDirection: ltr
...    widthFactor: expand
...    heightFactor: expand
...    child: RenderConstrainedBox#90ac1 relayoutBoundary=up2 NEEDS-PAINT
...      parentData: offset=Offset(55.7, 260.3) (can use size)
...      constraints: BoxConstraints(0.0<=w<=411.4, 0.0<=h<=820.6)
...      size: Size(300.0, 300.0)
...      additionalConstraints: BoxConstraints(w=300.0, h=300.0)
====================================================================================================

**Comment by AbdulrhmanSayedAli** [comment]
thanks for your help 
problem was solved and newer version of vitality is now available on pub.dev check it out

link : https://pub.dev/packages/vitality
