### ISSUE TITLE
 setState() called after dispose()

### ISSUE THREAD

**Issue by II11II** [AbdulrhmanSayedAli/vitality#3]
```App error: setState() called after dispose(): _VitalityState#eee0e(lifecycle state: defunct, not mounted)```

The timer is not cancelled after state is disposed
Please add this line inside ```_VitalityState```
```
  void dispose() {
    timer.cancel();
    super.dispose();
  }
  ```

**Comment by AbdulrhmanSayedAli** [comment]
thank you for your contribution 
this error has been fixed and a newer version of vitality is now available (1.0.4) .
